load(mext);

/* Alternate way to build without using chdir */

for package in [ "defmfun1", "maxdoc", "mext_defmfun1", "aex", "store" ] do
      load_in_subdir(["ibuild","mac"],[package]);

/* other third party packages adapted to mext */
for package in [ "nelder_mead", "alt_eigen", "pw", "discrete",
          "coma", "circuits", "implicit" ] do
          load_in_subdir(["ibuild","mac"],[package]);
