/* maxima script to print latex documentation for mext packages */

load(mext);

/*
   Some of these can be commented out. But because of dependencies, they
   may be loaded anyway.
*/

require(mext_defmfun1);
require(defmfun1);
require(discrete_aex);
require(alt_eigen);

/*
require(store);
require(quicklisp);
require(prime_pi);
require(nelder_mead);
*/

/*print_copyrights : true$ */
print_sections_latex("./thirdparty.tex");
