load(mext);

our_mext_list : mext_list();

our_test_list : [mext_system,aex,lists_aex,discrete_aex];
/* our_test_list : [mext_system,pw,implicit,aex,lists_aex]; */

if member("store", our_mext_list) then our_test_list :
        cons("store",our_test_list);

if member("prime_pi", our_mext_list) then our_test_list :
        cons("prime_pi",our_test_list);

mext_test(our_test_list);

kill(our_mext_list, our_test_list);
