/* Test 1 */
attributes(timing);
['hold_all]$

/* Test 2 */
numberp(first(timing()));
true$

/* Test 3 */
second(timing());
false$

/* Test 4 */
numberp(first(timing(1)));
true$

/* Test 5 */
second(timing(1));
1$

/* Test 6 */
timing(1,print->true);
1$

/* Test 7 */
numberp(timing(1,result->false));
true$

/* Test 8 */
with_output_to_string();
""$

/* Test 9 */
with_output_to_string(1);
""$

/* Test 10 */
is(with_output_to_string(print(1)) = printf(false,"~a ~%",1));
true$
